[package]
name = "guest_encrypt"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true

risc0-zkvm = { workspace = true,  default-features = false, features = ['std'] }
chacha20.workspace = true
