[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
chacha20.workspace = true
hex-literal.workspace = true

methods.workspace = true
risc0-zkvm = { workspace = true,  default-features = true }
tracing-subscriber.workspace = true
serde.workspace = true
